import moment from "moment";

// Date formatting functions
export const formatDate = (date, format = "DD/MM/YYYY") => {
  if (!date) return "";
  return moment(date).format(format);
};

export const formatDateTime = (date, format = "DD/MM/YYYY hh:mm A") => {
  if (!date) return "";
  return moment(date).format(format);
};

export const formatDateForInput = (date) => {
  if (!date) return "";
  return moment(date).format("YYYY-MM-DD");
};

export const formatDateForDisplay = (date) => {
  if (!date) return "";
  return moment(date).format("DD MMM YYYY");
};

export const formatDateForPDF = (date) => {
  if (!date) return "";
  return moment(date).format("DD/MM/YYYY");
};

export const formatTimeForPDF = (date) => {
  if (!date) return "";
  return moment(date).format("hh:mm A");
};

export const getCurrentDate = () => {
  return moment().format("YYYY-MM-DD");
};

export const getCurrentDateTime = () => {
  return moment().toDate();
};

// Currency formatting function
export const formatCurrency = (amount, currency = "₹") => {
  if (typeof amount !== "number") return `${currency}0.00`;
  return `${currency}${amount.toLocaleString("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
};

// App constants
export const CATEGORIES = [
  "Food",
  "Transport",
  "Accommodation",
  "Entertainment",
  "Shopping",
  "Bills",
  "Other",
];

export const APP_NAME = "RJ Expense Splitter";
export const APP_TAGLINE = "Split expenses with friends easily";

// PDF constants
export const PDF_TITLE = "EXPENSE RECEIPT";
export const PDF_SUBTITLE = "Group Settlement Summary";
export const PDF_FOOTER_TEXT = "Generated by RJ Expense Splitter";
export const PDF_FOOTER_SUBTEXT = "Keep for your records";

// Validation constants
export const MIN_USERS_REQUIRED = 2;
export const BALANCE_THRESHOLD = 0.01;

// UI Messages
export const MESSAGES = {
  NO_USERS:
    "No users added yet. Add at least 2 users to start tracking expenses.",
  NO_EXPENSES: "No expenses added yet",
  NO_EXPENSES_SUBTITLE: "Add your first expense to get started",
  ALL_SETTLED: "All settled! 🎉",
  ALL_SETTLED_SUBTITLE: "No one owes anyone money",
  WELCOME_TITLE: "Welcome to RJ Expense Splitter",
  WELCOME_SUBTITLE:
    "Add at least 2 users to start tracking and splitting expenses",
  FILL_REQUIRED_FIELDS: "Please fill all required fields",
  CONFIRM_DELETE: "Are you sure you want to delete this expense?",
  PAYMENT_MISMATCH: (totalPaid, expenseAmount) =>
    `Total payment amounts (₹${totalPaid}) must equal the expense amount (₹${expenseAmount})`,
};
